# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{enum_field}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebasti\303\241n Bernardo Galkin"]
  s.date = %q{2010-08-05}
  s.description = %q{enum_field}
  s.email = %q{sgalkin@grantaire.com.ar}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "enum_field.gemspec",
     "lib/enum_field.rb",
     "lib/enum_field/builder.rb",
     "lib/enum_field/define_enum.rb",
     "lib/enum_field/enumerated_attribute.rb",
     "lib/enum_field/railtie.rb",
     "test/enum_field_temp_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/shamne/enum_field_temp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Enables Active Record attributes to point to enum like objects, by saving in your database only an integer ID.}
  s.test_files = [
    "test/enum_field_temp_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
